version: '3.8'

services:
  backend:
    container_name: express-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://<username>:<password>@<host>.neon.tech/<dbname>?sslmode=require
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules